---
parser: "babel-eslint"

extends:
  - "airbnb"
  - "prettier"
  - "prettier/react"

plugins:
  - "prettier"

settings:
  import/resolver:
    babel-module: true

env:
  node: true
  browser: true

globals:
  __DEV__: true

rules:
  no-confusing-arrow: "off"

  prettier/prettier:
    - "error"
    - printWidth: 100
      tabWidth: 2
      trailingComma: "all"
      singleQuote: true

  import/prefer-default-export: "off"

  import/first:
    - "error"
    - absolute-first: false

  import/order:
    - "error"
    - groups:
      - ["builtin", "external"]
      - ["internal", "parent", "sibling", "index"]

  react/no-unused-prop-types: "off"
  react/require-default-props: "off"
  react/sort-comp: "off"

  react/jsx-filename-extension:
    - "error"
    - extensions:
      - ".js"

  jsx-a11y/href-no-hash: "off"
