#!/usr/bin/env node

require('babel-register');

const webpack = require('webpack');
const nodemon = require('nodemon');
const fsx = require('fs-extra');
const cp = require('child_process');
const path = require('path');

const { locations } = require('../config');
const serverConfig = require('../config/webpack/server').default;
const clientConfig = require('../config/webpack/client.prod').default;

const { NODE_ENV } = process.env;

const isDevelopment = NODE_ENV !== 'production';

if (isDevelopment) {
  console.log(`=> 🚧  Starting ${NODE_ENV} environment...`);
} else {
  console.log(`=> 🌎  Starting ${NODE_ENV} environment...`);
}

const clean = () => {
  console.log('=> 🗑  Cleaning...');
  const cleanScript = path.resolve(locations.src, 'scripts', 'clean');
  cp.exec(cleanScript);
  console.log('=> 🗑  Cleaned');
};

const copyFavicon = () => {
  console.log('=> 🔖  Copying favicon...');
  const src = path.resolve(locations.src, 'app', 'assets', 'favicon.ico');
  const dest = path.resolve(locations.public, 'favicon.ico');
  fsx.copySync(src, dest);
  console.log('=> 🔖  Copied');
};

const compileAndWatchServerBuild = () => {
  console.log('=> 🔨  Compiling server development build...');
  let initialCompile = true;
  return new Promise(resolve => {
    webpack(serverConfig).watch(null, (error, stats) => {
      if (error) return console.error(error);

      if (initialCompile) {
        initialCompile = false;
        console.log('=> 🔨  Server development build is compiled');
        return resolve();
      }

      return false;
    });
  });
};

const compileClientProductionBuild = () => {
  console.log('=> 🔨  Compiling client production build...');
  let initialCompile = true;
  return new Promise(resolve => {
    webpack(clientConfig).watch(null, (error, stats) => {
      if (error) return console.error(error);

      if (initialCompile) {
        initialCompile = false;
        console.log('=> 🔨  Client production build is compiled');
        return resolve();
      }

      return false;
    });
  });
};

const compileServerProductionBuild = () => {
  console.log('=> 🔨  Compiling server production build...');

  let initialServerCompile = true;
  return new Promise(resolve => {
    webpack(serverConfig).watch(null, (error, stats) => {
      if (error) return console.error(error);

      if (initialServerCompile) {
        initialServerCompile = false;
        console.log('=> 🔨  Server production build is compiled');
        return resolve();
      }

      return false;
    });
  });
};

const runHotServer = () =>
  new Promise(resolve => {
    console.log('=> 🔥  Starting HOT server...');
    const hotServer = path.resolve(locations.src, 'scripts', 'start:hot');

    cp.fork(hotServer).on('message', () => {
      console.log('=> 🔥  Client development builds are compiled');
      resolve();
    });
  });

const runAppServer = () => {
  console.log('=> 🚀  Starting WEB server...');

  const app = path.resolve(locations.serverBuild, 'app.js');
  const templates = path.resolve(locations.src, 'app', 'shell', 'server', 'templates');
  const manifest = path.resolve(locations.assets, 'modules.manifest.json');

  if (!fsx.existsSync(app)) {
    console.error(`🚨  Can't find app build at path: ${app}`);
    process.exit(1);
  }

  if (!fsx.existsSync(templates)) {
    console.error(`🚨  Can't find directory with server templates at path: ${templates}`);
    process.exit(1);
  }

  if (!fsx.existsSync(manifest)) {
    console.error(`🚨  Can't find modules manifest at path: ${manifest}`);
    process.exit(1);
  }

  nodemon({
    script: app,
    watch: [app, templates, manifest],
    ext: 'js json',
  });
};

const runDevelopment = async () => {
  await clean();
  await runHotServer();
  await copyFavicon();
  await compileAndWatchServerBuild();
  await runAppServer();
};

const runProduction = async () => {
  await clean();
  await compileClientProductionBuild();
  await compileServerProductionBuild();
  await runAppServer();
};

isDevelopment ? runDevelopment() : runProduction();
